# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-07 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lunbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('wen', models.CharField(max_length=50)),
                ('alt', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Lunbo',
            },
        ),
    ]
